#!/usr/bin/env python3
"""Inject the site-wide navigation into every page: a top nav bar, breadcrumbs
(visible + BreadcrumbList JSON-LD), a "Nearby trails" block on each trail and a
"More guides" block of descriptive links to the guide pages.

Why this exists
---------------
A Screaming Frog crawl (2026-09-28) showed the static link graph was too thin:
the fees and booking-from-abroad pages were reachable only from each other (8
orphans), most spokes had just 5 inbound links (4 language switchers + the
board), and trail pages had no route to their neighbours. This script gives
every page the same crawlable links, all as plain `<a href>` in the raw HTML.

Four marker-delimited blocks, replaced in place on every run (idempotent):

  SITE-NAV-HEAD     before </head>   CSS + BreadcrumbList JSON-LD
  SITE-NAV          in <header>      nav bar + breadcrumb trail
  SITE-NAV-RELATED  before <footer>  4 nearest trails (trail pages only), plus an "In our
                                     guides" line linking the list pages (HUBS) that cover
                                     this trail, when any do
  SITE-NAV-GUIDES   before <footer>  "More guides": links to the pages in GUIDES that the
                                     page's own copy doesn't already link (RELATED_GUIDES
                                     picks them per page; the homepage lists all). Empty
                                     markers placed by hand (homepages) keep their spot.

"Nearby" is real distance between trailheads, from the coordinates embedded in
the Visit Madeira hiking index (the same source `update_status.py` parses).
Fails loud if that index can't be read.

Re-run after `gen_spokes.py` (which calls this itself) or whenever a trail or
page is added:

    python scripts/gen_site_nav.py
    python scripts/gen_site_nav.py --dry-run [OUTDIR]   # a few sample pages -> OUTDIR, repo untouched

`trail_coords()` is importable (gen_spokes.py uses it); importing this module has no
side effects.
"""

import functools
import json
import math
import pathlib
import re
import sys

import requests

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The Visit Madeira hiking index and its row pattern (same source as
# update_status.py; kept local so this script doesn't depend on that module's
# internal names). Rows: ["PR X - Name", lat, lon, n, "img", "url", "", bool, {"label":"..."}]
TRAILS_INDEX = "https://visitmadeira.com/en/what-to-do/nature-seekers/activities/hiking/"
TRAIL_RE = re.compile(
    r'\["(PR[^"]+?)",(-?\d+\.\d+),(-?\d+\.\d+),\d+,"[^"]*","[^"]*","[^"]*",'
    r'(?:true|false),\{"label":"([^"]+)"'
)
UA = {"User-Agent": "Mozilla/5.0 (compatible; LevadinhoStatusBot/5.0; +https://levadinho-madeira.com)"}

BASE = "https://levadinho-madeira.com"
LANGS = ("en", "pt", "fr", "de", "pl")
PREFIX = {"en": "", "pt": "/pt", "fr": "/fr", "de": "/de", "pl": "/pl"}
N_RELATED = 4

MARK = {
    k: ("<!-- {}:START (generated by scripts/gen_site_nav.py) -->".format(k),
        "<!-- {}:END -->".format(k))
    for k in ("SITE-NAV-HEAD", "SITE-NAV", "SITE-NAV-RELATED", "SITE-NAV-GUIDES")
}

# Nav bar entries: key -> (path within the language folder, label per language).
# Kept to six so it stays one line on desktop; every other guide is linked from
# the generated "More guides" block (GUIDES below) on the homepage and related pages.
NAV = [
    ("trails", "/", {"en": "All trails", "pt": "Todos os percursos", "fr": "Tous les sentiers", "de": "Alle Wanderwege", "pl": "Wszystkie szlaki"}),
    ("pr1", "/pr1/", {"en": "PR1 today", "pt": "PR1 hoje", "fr": "PR1 aujourd'hui", "de": "PR1 heute", "pl": "PR1 dziś"}),
    ("fees", "/hiking-fees.html", {"en": "Fees 2026", "pt": "Taxas 2026", "fr": "Tarifs 2026", "de": "Gebühren 2026", "pl": "Opłaty 2026"}),
    ("booking", "/simplifica-booking/", {"en": "How to book", "pt": "Como reservar", "fr": "Réserver", "de": "Buchen", "pl": "Rezerwacja"}),
    ("back", "/getting-back.html", {"en": "Getting back from PR1", "pt": "Regressar do PR1", "fr": "Retour du PR1",
                                    "de": "Rückweg vom PR1", "pl": "Powrót z PR1"}),
    ("best", "/best-levada-walks/", {"en": "Best levadas", "pt": "Melhores levadas", "fr": "Meilleures levadas",
                                     "de": "Schönste Levadas", "pl": "Najlepsze lewady"}),
]

# Guide pages (not trails). key -> path, breadcrumb parent key (None = homepage),
# short breadcrumb label, and a descriptive link text matching the query the page targets
# (used in the "More guides" block).
GUIDES = [
    ("pr1", "/pr1/", None, None,
     {"en": "Is PR1 open today?", "pt": "O PR1 está aberto hoje?", "fr": "Le PR1 est-il ouvert aujourd'hui ?",
      "de": "Ist der PR1 heute geöffnet?", "pl": "Czy PR1 jest dziś otwarty?"}),
    ("fees", "/hiking-fees.html", None, None,
     {"en": "Madeira hiking fees 2026", "pt": "Taxas dos percursos pedestres 2026", "fr": "Tarifs des randonnées à Madère 2026",
      "de": "Wandergebühren auf Madeira 2026", "pl": "Opłaty za szlaki na Maderze 2026"}),
    ("permit", "/do-i-need-a-permit/", None,
     {"en": "Do I need a permit?", "pt": "É preciso autorização?", "fr": "Faut-il un permis ?", "de": "Brauche ich eine Genehmigung?",
      "pl": "Czy potrzebne jest pozwolenie?"},
     {"en": "Do I need a permit for levada walks?", "pt": "É preciso autorização para fazer levadas?",
      "fr": "Faut-il un permis pour les levadas ?", "de": "Brauche ich eine Genehmigung für Levada-Wanderungen?",
      "pl": "Czy na lewady potrzebne jest pozwolenie?"}),
    ("booking", "/simplifica-booking/", None,
     {"en": "SIMplifica booking", "pt": "Reserva no SIMplifica", "fr": "Réservation SIMplifica", "de": "SIMplifica-Buchung",
      "pl": "Rezerwacja SIMplifica"},
     {"en": "SIMplifica trail booking, step by step", "pt": "Reservar percursos no SIMplifica, passo a passo",
      "fr": "Réserver un sentier sur SIMplifica, pas à pas", "de": "Wanderweg auf SIMplifica buchen, Schritt für Schritt",
      "pl": "Rezerwacja szlaku w SIMplifica krok po kroku"}),
    ("abroad", "/simplifica-from-abroad.html", None,
     {"en": "Booking from abroad", "pt": "Reservar do estrangeiro", "fr": "Réserver depuis l'étranger",
      "de": "Buchen aus dem Ausland", "pl": "Rezerwacja z zagranicy"},
     {"en": "SIMplifica not working from abroad?", "pt": "O SIMplifica não funciona no estrangeiro?",
      "fr": "SIMplifica ne marche pas depuis l'étranger ?", "de": "SIMplifica funktioniert im Ausland nicht?",
      "pl": "SIMplifica nie działa z zagranicy?"}),
    ("back", "/getting-back.html", None, None,
     {"en": "Getting back from Pico Ruivo without a car", "pt": "Regressar do Pico Ruivo sem carro",
      "fr": "Revenir du Pico Ruivo sans voiture", "de": "Vom Pico Ruivo ohne Auto zurück", "pl": "Powrót z Pico Ruivo bez samochodu"}),
    ("sunrise", "/pr1-sunrise-transport/", "pr1",
     {"en": "Sunrise transport", "pt": "Transporte ao nascer do sol", "fr": "Transport au lever du soleil",
      "de": "Anfahrt zum Sonnenaufgang", "pl": "Dojazd na wschód słońca"},
     {"en": "PR1 sunrise transfer: bus, shuttle, taxi or car", "pt": "Nascer do sol no Pico do Areeiro: autocarro, transfer, táxi ou carro",
      "fr": "Lever du soleil au Pico do Arieiro : bus, navette, taxi ou voiture",
      "de": "Sonnenaufgang am Pico do Arieiro: Bus, Shuttle, Taxi oder Auto",
      "pl": "Wschód słońca na Pico do Arieiro: autobus, bus, taksówka czy auto"}),
    ("oneway", "/pr1-one-way/", "pr1",
     {"en": "Is PR1 one-way?", "pt": "PR1 em sentido único?", "fr": "PR1 à sens unique ?", "de": "PR1 nur in eine Richtung?",
      "pl": "PR1 jednokierunkowy?"},
     {"en": "Is PR1 one-way? Direction and return, 2026", "pt": "O PR1 é em sentido único? Direção e regresso, 2026",
      "fr": "Le PR1 est-il à sens unique ? Sens et retour, 2026", "de": "Ist der PR1 nur in eine Richtung begehbar? Richtung & Rückweg 2026",
      "pl": "Czy PR1 jest jednokierunkowy? Kierunek i powrót, 2026"}),
    ("weather", "/pico-do-areeiro-weather/", "pr1",
     {"en": "Pico do Areeiro weather", "pt": "Tempo no Pico do Areeiro", "fr": "Météo du Pico do Arieiro",
      "de": "Wetter am Pico do Arieiro", "pl": "Pogoda na Pico do Arieiro"},
     {"en": "Pico do Areeiro weather & live webcam", "pt": "Tempo e webcam em direto do Pico do Areeiro",
      "fr": "Météo et webcam en direct du Pico do Arieiro", "de": "Pico do Arieiro: Wetter & Webcam live",
      "pl": "Pico do Arieiro: pogoda i kamera na żywo"}),
    ("free", "/free-walks/", None,
     {"en": "Free walks", "pt": "Trilhos gratuitos", "fr": "Randonnées gratuites", "de": "Wandern ohne Gebühr",
      "pl": "Darmowe szlaki"},
     {"en": "Free walks in Madeira: no ticket needed", "pt": "Trilhos gratuitos na Madeira: sem bilhete",
      "fr": "Randonnées gratuites à Madère : sans billet", "de": "Wandern auf Madeira ohne Gebühr und ohne Ticket",
      "pl": "Darmowe szlaki na Maderze: bez biletu"}),
    ("bus", "/levadas-by-bus/", None,
     {"en": "Levadas by bus", "pt": "Levadas de autocarro", "fr": "Levadas en bus", "de": "Levadas mit dem Bus",
      "pl": "Lewady autobusem"},
     {"en": "Levadas by bus from Funchal: which trails", "pt": "Levadas de autocarro a partir do Funchal",
      "fr": "Levadas en bus depuis Funchal : quels sentiers", "de": "Levadas mit dem Bus ab Funchal",
      "pl": "Lewady autobusem z Funchal: które szlaki"}),
    ("best", "/best-levada-walks/", None,
     {"en": "Best levada walks", "pt": "Melhores levadas", "fr": "Meilleures levadas", "de": "Schönste Levadas",
      "pl": "Najpiękniejsze lewady"},
     {"en": "Best levada walks in Madeira", "pt": "As melhores levadas da Madeira", "fr": "Les meilleures levadas de Madère",
      "de": "Die schönsten Levadas auf Madeira", "pl": "Najpiękniejsze lewady na Maderze"}),
    ("easy", "/easy-levadas-no-vertigo/", "best",
     {"en": "Easy levadas, no vertigo", "pt": "Levadas fáceis sem vertigens", "fr": "Levadas faciles sans vertige",
      "de": "Leichte Levadas ohne Schwindelgefahr", "pl": "Łatwe lewady bez lęku wysokości"},
     {"en": "Easy levada walks without vertigo", "pt": "Levadas fáceis sem vertigens", "fr": "Levadas faciles sans vertige",
      "de": "Leichte Levadas ohne Schwindelgefahr", "pl": "Łatwe lewady bez lęku wysokości"}),
    ("tunnels", "/levadas-with-tunnels/", "best",
     {"en": "Levadas with tunnels", "pt": "Levadas com túneis", "fr": "Levadas à tunnels", "de": "Levadas mit Tunneln",
      "pl": "Lewady z tunelami"},
     {"en": "Levadas with tunnels: when to bring a torch", "pt": "Levadas com túneis: quando levar lanterna",
      "fr": "Levadas à tunnels : quand prendre une lampe", "de": "Levadas mit Tunneln: wann Sie eine Lampe brauchen",
      "pl": "Lewady z tunelami: kiedy zabrać latarkę"}),
    ("closures", "/trail-closures/", None,
     {"en": "Trail closures", "pt": "Percursos encerrados", "fr": "Sentiers fermés", "de": "Gesperrte Wege",
      "pl": "Zamknięte szlaki"},
     {"en": "Which Madeira trails are closed today?", "pt": "Que percursos estão encerrados hoje?",
      "fr": "Quels sentiers sont fermés aujourd'hui ?", "de": "Welche Wanderwege sind heute gesperrt?",
      "pl": "Które szlaki są dziś zamknięte?"}),
    ("about", "/about/", None,
     {"en": "About", "pt": "Sobre", "fr": "À propos", "de": "Über uns", "pl": "O nas"},
     {"en": "About Levadinho: sources and method", "pt": "Sobre o Levadinho: fontes e método",
      "fr": "À propos de Levadinho : sources et méthode", "de": "Über Levadinho: Quellen und Methode",
      "pl": "O Levadinho: źródła i metoda"}),
]
GUIDE = {g[0]: g for g in GUIDES}
# Which guides each page links to in its "More guides" block (targets the page already
# links to in its own copy are dropped, so the block never repeats a "Next steps" link).
RELATED_GUIDES = {
    "home": ["closures", "pr1", "oneway", "fees", "permit", "free", "booking", "abroad", "back", "sunrise", "weather", "best", "easy", "tunnels", "bus"],
    "pr1": ["oneway", "sunrise", "weather", "back", "booking", "fees", "permit", "closures"],
    "fees": ["permit", "free", "booking", "abroad", "best", "pr1"],
    "permit": ["free", "booking", "fees", "best", "easy", "tunnels"],
    "booking": ["abroad", "permit", "fees", "pr1", "best"],
    "abroad": ["booking", "permit", "fees", "pr1"],
    "back": ["bus", "oneway", "sunrise", "weather", "pr1", "booking"],
    "sunrise": ["weather", "back", "bus", "oneway", "pr1", "booking"],
    "weather": ["pr1", "sunrise", "back", "best"],
    "best": ["easy", "tunnels", "bus", "closures", "permit", "booking", "fees"],
    "easy": ["best", "tunnels", "free", "permit", "booking"],
    "tunnels": ["best", "easy", "permit", "booking"],
    "oneway": ["back", "sunrise", "pr1", "booking", "fees"],
    "free": ["permit", "fees", "booking", "easy", "best", "bus"],
    "bus": ["back", "sunrise", "free", "best", "easy", "booking"],
    "closures": ["pr1", "best", "fees", "booking", "permit", "about"],
    "about": ["closures", "pr1", "fees", "booking", "permit", "best"],
    "spoke": ["closures", "best", "easy", "tunnels", "booking", "fees", "permit"],
    "spoke-pr1": ["pr1", "oneway", "back", "sunrise", "weather", "booking", "fees"],   # PR1.2 Pico Ruivo
}
GUIDES_H = {"en": "More guides", "pt": "Mais guias", "fr": "Autres guides", "de": "Weitere Ratgeber", "pl": "Więcej poradników"}
N_GUIDES_MIN = 2   # fewer new links than this -> no block

NAV_ARIA = {"en": "Site", "pt": "Site", "fr": "Site", "de": "Website", "pl": "Serwis"}
CRUMB_ARIA = {"en": "Breadcrumb", "pt": "Navegação estrutural", "fr": "Fil d'Ariane", "de": "Brotkrümelnavigation", "pl": "Ścieżka nawigacji"}
HOME = {"en": "Home", "pt": "Início", "fr": "Accueil", "de": "Startseite", "pl": "Strona główna"}
NEARBY = {"en": "Nearby trails", "pt": "Percursos próximos", "fr": "Sentiers à proximité", "de": "Wanderwege in der Nähe", "pl": "Szlaki w pobliżu"}
NEARBY_SUB = {"en": "Closest trailheads — each has its own live status.",
              "pt": "Os pontos de partida mais próximos — cada um com o seu estado em direto.",
              "fr": "Les départs les plus proches — chacun avec son état en direct.",
              "de": "Die nächstgelegenen Startpunkte — jeweils mit eigenem Live-Status.",
              "pl": "Najbliższe punkty startowe — każdy z własnym stanem na żywo."}
KM = {"en": "{} km away", "pt": "a {} km", "fr": "à {} km", "de": "{} km entfernt", "pl": "{} km stąd"}
# List pages that cover individual trails. A trail page links back to each one whose
# English copy has the trail's badge / static-status marker / a link to its page.
HUBS = ("best", "easy", "tunnels", "bus")
LISTED = {"en": "In our guides:", "pt": "Nos nossos guias:", "fr": "Dans nos guides :",
          "de": "In unseren Ratgebern:", "pl": "W naszych poradnikach:"}
SAME = {"en": "Same trailhead", "pt": "Mesmo ponto de partida", "fr": "Même point de départ", "de": "Gleicher Startpunkt", "pl": "Ten sam punkt startowy"}


def dist_label(lang, d):
    if d < 0.5:
        return SAME[lang]
    n = str(round(d, 1) if d < 10 else round(d))
    return KM[lang].format(n if lang == "en" else n.replace(".", ","))

CSS = """<style>
.sitenav{display:flex;flex-wrap:wrap;gap:4px 16px;margin:10px 0 8px;font-size:13.5px}
.sitenav a{color:var(--ink);font-weight:650;text-decoration:none;border-bottom:2px solid transparent;padding-bottom:1px}
.sitenav a:hover{border-bottom-color:var(--line,#E3E1D8)}
.sitenav a[aria-current="page"]{border-bottom-color:var(--way-yellow,#E8B71A)}
.crumbs ol{list-style:none;padding:0;margin:0 0 4px;display:flex;flex-wrap:wrap}
.crumbs li{margin:0;font-size:12.5px;color:var(--ink-soft)}
.crumbs li+li::before{content:"\\203A";margin:0 7px;color:var(--ink-soft)}
.crumbs a{color:var(--ink-soft)}
.related ul{list-style:none;padding:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
@media (max-width:480px){.related ul{grid-template-columns:1fr}}
.related li{margin:0}
.related li a{display:block;height:100%;background:var(--card,#fff);border:1px solid var(--line,#E3E1D8);border-radius:10px;
  padding:10px 12px;text-decoration:none;color:var(--ink);font-weight:700;font-size:14.5px;line-height:1.3}
.related li a:hover{border-color:var(--ink-soft)}
.related li a span{display:block;margin-top:3px;font-weight:400;font-size:12.5px;color:var(--ink-soft)}
.related p{color:var(--ink-soft);font-size:14px}
.guides{margin-top:22px}
.guides ul{list-style:none;padding:0;margin:8px 0 0;display:flex;flex-wrap:wrap;gap:6px 8px}
.guides li{margin:0}
.guides a{display:inline-block;border:1px solid var(--line,#E3E1D8);border-radius:999px;padding:5px 11px;font-size:13.5px;
  font-weight:650;color:var(--ink);text-decoration:none;background:var(--card,#fff)}
.guides a:hover{border-color:var(--ink-soft)}
a.tname{color:inherit;text-decoration:none}
a.tname:hover{text-decoration:underline}
</style>"""


@functools.lru_cache(maxsize=None)
def trail_coords():
    """code -> (lat, lon) of each trailhead, from the Visit Madeira index (e.g. "PR6").
    Fetched once per process; raises on HTTP errors."""
    r = requests.get(TRAILS_INDEX, headers=UA, timeout=30)
    r.raise_for_status()
    out = {}
    for m in TRAIL_RE.finditer(r.text):
        try:
            raw = json.loads('"' + m.group(1) + '"')
        except Exception:
            raw = m.group(1)
        code = (raw.split(" - ", 1)[0] if " - " in raw else raw).replace(" ", "")
        out.setdefault(code, (float(m.group(2)), float(m.group(3))))
    return out


def km(a, b):
    """Great-circle distance in km."""
    la1, lo1, la2, lo2 = map(math.radians, (*a, *b))
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 2 * 6371 * math.asin(math.sqrt(h))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def href(lang, path):
    """Root-relative URL of `path` (an English path) in `lang`'s folder."""
    return PREFIX[lang] + path


def file_for(lang, path):
    rel = path.lstrip("/")
    rel = rel + "index.html" if rel.endswith("/") or rel == "" else rel
    return ROOT / PREFIX[lang].lstrip("/") / rel if PREFIX[lang] else ROOT / rel


def replace_block(html, key, body, anchor_re, where, path):
    """Put `body` between `key`'s markers: in place if present, otherwise
    before/after the first match of `anchor_re`."""
    start, end = MARK[key]
    block = "{}\n{}\n{}".format(start, body, end)
    if start in html:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda _: block, html, count=1, flags=re.S)
    m = re.search(anchor_re, html, flags=re.S)
    if not m:
        sys.exit("FATAL: anchor {!r} for {} not found in {}".format(anchor_re, key, path))
    i = m.start() if where == "before" else m.end()
    return html[:i] + block + "\n" + html[i:]


def nav_html(lang, current, crumbs):
    items = "\n".join(
        '    <a href="{}"{}>{}</a>'.format(href(lang, p), ' aria-current="page"' if k == current else "", esc(lbl[lang]))
        for k, p, lbl in NAV
    )
    out = '  <nav class="sitenav" aria-label="{}">\n{}\n  </nav>'.format(NAV_ARIA[lang], items)
    if crumbs:
        lis = []
        for i, (name, url) in enumerate(crumbs):
            if i == len(crumbs) - 1:
                lis.append('      <li aria-current="page">{}</li>'.format(esc(name)))
            else:
                lis.append('      <li><a href="{}">{}</a></li>'.format(url, esc(name)))
        out += '\n  <nav class="crumbs" aria-label="{}">\n    <ol>\n{}\n    </ol>\n  </nav>'.format(
            CRUMB_ARIA[lang], "\n".join(lis))
    return out


def head_html(crumbs):
    if not crumbs:
        return CSS
    ld = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": BASE + url}
            for i, (name, url) in enumerate(crumbs)
        ],
    }
    return CSS + '\n<script type="application/ld+json">\n{}\n</script>'.format(
        json.dumps(ld, ensure_ascii=False, indent=2))


def strip_generated(html):
    """`html` without the generated blocks (site nav, CTA), so only the page's own copy is left."""
    for k in MARK:
        start, end = MARK[k]
        html = re.sub(re.escape(start) + r".*?" + re.escape(end), "", html, flags=re.S)
    return re.sub(r"<!--\s*LEVADINHO-CTA:START.*?LEVADINHO-CTA:END\s*-->", "", html, flags=re.S)


def hub_listing():
    """hub key -> (set of trail codes, set of trail paths) mentioned in its English page."""
    out = {}
    for k in HUBS:
        f = file_for("en", GUIDE[k][1])
        if not f.exists():
            sys.exit("FATAL: hub page {} not found".format(f))
        body = strip_generated(f.read_text(encoding="utf-8"))
        codes = set(re.findall(r'data-(?:code|trail)="([^"]+)"', body))
        codes |= set(re.findall(r"STATIC-STATUS:([A-Z0-9.]+):START", body))
        paths = set(re.findall(r'<a\b[^>]*href="(/[^"#?]*)', body))
        out[k] = (codes, paths)
    return out


def hubs_for(t, listing):
    """The hub keys whose page covers trail `t` (a status.json trails[] entry), in HUBS order."""
    return [k for k in HUBS if t["code"] in listing[k][0] or t["page"] in listing[k][1]]


def listed_html(lang, hubs):
    links = " · ".join('<a href="{}">{}</a>'.format(href(lang, GUIDE[k][1]), esc(GUIDE[k][3][lang])) for k in hubs)
    return '  <p class="listed">{} {}</p>'.format(LISTED[lang], links)


def related_html(lang, near, hubs=()):
    items = "\n".join(
        '    <li><a href="{}">{} {}<span>{}</span></a></li>'.format(
            href(lang, t["page"]), esc(t["code"]), esc(t["name"]), dist_label(lang, d))
        for t, d in near
    )
    listed = "\n" + listed_html(lang, hubs) if hubs else ""
    return ('<section class="related" id="nearby">\n  <h2>{}</h2>\n  <p>{}</p>\n  <ul>\n{}\n  </ul>{}\n</section>'
            .format(NEARBY[lang], NEARBY_SUB[lang], items, listed))


def guides_html(lang, keys, html):
    """The "More guides" block: descriptive links to the guide pages in `keys`, minus the
    ones the page already links to outside the generated blocks. None if too few remain."""
    body = strip_generated(html)
    linked = set(re.findall(r'<a\b[^>]*href="([^"#?]+)', body))
    keys = [k for k in keys if href(lang, GUIDE[k][1]) not in linked]
    if len(keys) < N_GUIDES_MIN:
        return None
    items = "\n".join('    <li><a href="{}">{}</a></li>'.format(href(lang, GUIDE[k][1]), esc(GUIDE[k][4][lang])) for k in keys)
    return '<nav class="guides" aria-label="{0}">\n  <h2>{0}</h2>\n  <ul>\n{1}\n  </ul>\n</nav>'.format(GUIDES_H[lang], items)


def drop_block(html, key):
    start, end = MARK[key]
    return re.sub(r"\n?" + re.escape(start) + r".*?" + re.escape(end), "", html, flags=re.S)


SKIPPED = []
# --dry-run: {repo file: None} for the sample pages; results go to DRY_OUT, the repo is untouched.
DRY_PAGES = ("25-fontes/index.html", "pt/25-fontes/index.html", "levada-do-risco/index.html",
             "pico-ruivo/index.html", "de/pr1/index.html", "pl/levada-velha-do-rabacal/index.html")
DRY_OUT = None


def transform(html, path, lang, current, crumbs, near=None, guides=None, hubs=(),
              header_anchor=r'<nav class="langs"[^>]*>.*?</nav>\n'):
    html = replace_block(html, "SITE-NAV-HEAD", head_html(crumbs), r"</head>", "before", path)
    html = replace_block(html, "SITE-NAV", nav_html(lang, current, crumbs), header_anchor, "after", path)
    if near:
        html = replace_block(html, "SITE-NAV-RELATED", related_html(lang, near, hubs), r"<footer", "before", path)
    g = guides_html(lang, RELATED_GUIDES[guides], html) if guides else None
    if g:
        html = replace_block(html, "SITE-NAV-GUIDES", g, r"<footer", "before", path)
    else:
        html = drop_block(html, "SITE-NAV-GUIDES")
    return html


def process(path, lang, current, crumbs, near=None, guides=None, hubs=(),
            header_anchor=r'<nav class="langs"[^>]*>.*?</nav>\n'):
    rel = str(path.relative_to(ROOT))
    if DRY_OUT is not None and rel not in DRY_PAGES:
        return False
    if not path.exists():
        # A language's page may not exist yet -- skip it and say so; re-run once the file is there.
        SKIPPED.append(rel)
        return False
    html = path.read_text(encoding="utf-8")
    args = (path, lang, current, crumbs, near, guides, hubs, header_anchor)
    out = transform(html, *args)
    if DRY_OUT is None:
        path.write_text(out, encoding="utf-8")
        return True
    dest = DRY_OUT / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(out, encoding="utf-8")
    again = transform(out, *args)
    print("dry-run {} -> {} (second pass {})".format(rel, dest, "identical" if again == out else "DIFFERS"))
    return True


def crumbs_for(lang, key):
    """Home > [parent guide >] this guide."""
    home = (HOME[lang], href(lang, "/"))
    _, path, parent, short, long_ = GUIDE[key]
    label = (short or {}).get(lang) or nav_label(key, lang) or long_[lang]
    out = [home]
    if parent:
        pp = GUIDE[parent]
        out.append(((pp[3] or {}).get(lang) or nav_label(parent, lang) or pp[4][lang], href(lang, pp[1])))
    out.append((label, href(lang, path)))
    return out


def nav_label(key, lang):
    for k, _, lbl in NAV:
        if k == key:
            return lbl[lang]
    return None


def main():
    global DRY_OUT
    if "--dry-run" in sys.argv:
        i = sys.argv.index("--dry-run")
        nxt = sys.argv[i + 1] if len(sys.argv) > i + 1 else None
        DRY_OUT = pathlib.Path(nxt or "gen_site_nav_dry").resolve()
    trails = json.loads((ROOT / "status.json").read_text())["trails"]
    coords = trail_coords()
    missing = [t["code"] for t in trails if t["code"] not in coords or not t.get("page")]
    if missing:
        sys.exit("FATAL: no coordinates or page for {}".format(missing))

    def nearest(t):
        others = [(o, km(coords[t["code"]], coords[o["code"]])) for o in trails if o["page"] != t["page"]]
        return sorted(others, key=lambda x: x[1])[:N_RELATED]

    listing = hub_listing()
    nav_keys = {k for k, _, _ in NAV}
    n = 0
    for lang in LANGS:
        home = (HOME[lang], href(lang, "/"))   # the homepage is the trails board
        for t in trails:
            name = "{} {}".format(t["code"], t["name"])
            is_pr1 = t["page"] == "/pr1/"
            n += process(file_for(lang, t["page"]), lang, "pr1" if is_pr1 else None,
                         [home, (name, href(lang, t["page"]))], nearest(t),
                         guides="pr1" if is_pr1 else ("spoke-pr1" if t["code"] == "PR1.2" else "spoke"),
                         hubs=hubs_for(t, listing))
        n += process(file_for(lang, "/"), lang, "trails", None, guides="home")
        for key, p, *_ in GUIDES:
            if key == "pr1":
                continue   # a trail page, handled above
            n += process(file_for(lang, p), lang, key if key in nav_keys else None, crumbs_for(lang, key), guides=key)
    # English-only privacy page: nav bar only, no language switcher to anchor on.
    process(ROOT / "privacy" / "index.html", "en", None, None, header_anchor=r"<header>\n")
    print("site nav written to {} pages{}".format(n, " (dry run, repo untouched)" if DRY_OUT else " (+ privacy)"))
    if SKIPPED:
        print("skipped {} missing page(s) -- re-run once they exist: {}".format(len(SKIPPED), ", ".join(SKIPPED)))


if __name__ == "__main__":
    main()
