#!/usr/bin/env python3
"""Say who is behind the site (owner, 2026-10-05).

Writes, between marker comments (idempotent, re-run any time):
  * OWNER-LINE  -- a last line inside every page's <footer>, in the page's language:
                   "This is a personal project of Mayke De Freitas Santos, 2026. All Rights Reserved.
                   Enquiries: hello at levadinho-madeira dot com" (address spelled out on purpose).
  * OWNER-SIG   -- the owner's name under "Why I built this" on the five homepages.
  * OWNER-SCHEMA -- a WebSite + Person JSON-LD block in the head of the five homepages.

Called by gen_spokes.py and gen_bus_hub.py after they rewrite pages. Skips bot/, the
trails/ forwarding stubs and the local-only folders.

    python scripts/gen_owner.py
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
NAME = "Mayke De Freitas Santos"
SKIP = ("bot", "seo_research", "reports", "google_search_console", "trails", ".git", ".claude")

LINE = {
    "en": f"This is a personal project of {NAME}, 2026. All Rights Reserved. Enquiries: hello at levadinho-madeira dot com",
    "pt": f"Este é um projeto pessoal de {NAME}, 2026. Todos os direitos reservados. Contactos: hello arroba levadinho-madeira ponto com",
    "fr": f"Ceci est un projet personnel de {NAME}, 2026. Tous droits réservés. Contact : hello arobase levadinho-madeira point com",
    "de": f"Dies ist ein privates Projekt von {NAME}, 2026. Alle Rechte vorbehalten. Anfragen: hello at levadinho-madeira Punkt com",
    "pl": f"To prywatny projekt {NAME}, 2026. Wszelkie prawa zastrzeżone. Kontakt: hello małpa levadinho-madeira kropka com",
}
HOMES = {"index.html": "en", "pt/index.html": "pt", "fr/index.html": "fr", "de/index.html": "de", "pl/index.html": "pl"}
HOME_URL = {"en": "/", "pt": "/pt/", "fr": "/fr/", "de": "/de/", "pl": "/pl/"}
BASE = "https://levadinho-madeira.com"


def mark(key):
    return f"<!-- {key}:START (generated by scripts/gen_owner.py) -->", f"<!-- {key}:END -->"


def put(html, key, content, anchor_re, before=True):
    """Replace the marked block, or insert it before/after the first anchor match."""
    start, end = mark(key)
    block = start + content + end
    pat = re.compile(re.escape(start.split(" (")[0]) + r".*?" + re.escape(end), re.S)
    if pat.search(html):
        return pat.sub(lambda m: block, html, count=1)
    m = re.search(anchor_re, html)
    if not m:
        return html
    i = m.start() if before else m.end()
    return html[:i] + block + html[i:]


def schema(lang):
    data = {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "WebSite", "@id": BASE + "/#website", "name": "Levadinho", "alternateName": "Levadinho Madeira",
             "url": BASE + HOME_URL[lang], "inLanguage": lang, "publisher": {"@id": BASE + "/#owner"}},
            {"@type": "Person", "@id": BASE + "/#owner", "name": NAME, "url": BASE + "/"},
        ],
    }
    return '\n<script type="application/ld+json">\n' + json.dumps(data, ensure_ascii=False, indent=1) + "\n</script>\n"


def main():
    changed = 0
    for path in sorted(ROOT.rglob("*.html")):
        rel = path.relative_to(ROOT)
        if rel.parts[0] in SKIP or (len(rel.parts) > 1 and rel.parts[1] == "trails"):
            continue
        s = path.read_text(encoding="utf-8")
        if "</footer>" not in s:
            continue
        m = re.search(r"<html[^>]*\blang=[\"']?([a-zA-Z]{2})", s)
        lang = (m.group(1).lower() if m else "en")
        lang = lang if lang in LINE else "en"
        new = put(s, "OWNER-LINE", f'<span class="owner" style="display:block;margin-top:6px">{LINE[lang]}</span>',
                  r"</footer>")
        if str(rel) in HOMES:
            new = put(new, "OWNER-SIG", f'<p class="sig" style="text-align:right;font-style:italic">— {NAME}</p>',
                      r'(?s)<div class="why">.*?</p>\s*', before=False)
            new = put(new, "OWNER-SCHEMA", schema(HOMES[str(rel)]), r"</head>")
        if new != s:
            path.write_text(new, encoding="utf-8")
            changed += 1
    print(f"gen_owner: {changed} page(s) updated")


if __name__ == "__main__":
    main()
