#!/usr/bin/env python3
"""Levadinho QR codes (owner, 2026-10-08): printable codes that open a page and tell it the visitor scanned one.

For each code in CODES it writes
  q/<code>/index.html   the short link the QR encodes (https://levadinho-madeira.com/q/<code>/): picks the visitor's
                        language from the phone (en/pt/fr/de/pl, else English) and redirects to the target page with
                        #qr=<code>. noindex, not in the sitemap, no analytics of its own (the target page counts the
                        scan, see /qr.js and /engage.js). Search engines ignore the #, so the target keeps one URL.
  q/<code>/qr.svg       the code to print (vector), and q/<code>/qr.png (1,200 px) for posters and stickers.
It also makes sure every target page loads /qr.js in its <head> (QR-HEAD markers), in all 5 languages.

Codes are per page for now; per-spot codes (a lido, a cable-car station) are a later step: add a code with the
same target, and the scan is counted and passed to the page under its own name.
Idempotent. Run from anywhere: python3 scripts/gen_qr.py
"""
import os
import re
import sys

import qrcode
from qrcode.image.svg import SvgPathImage

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from site_entity import BASE, LANGS, PREFIX  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODES = {            # code -> target path (language-neutral, English root form)
    "funchal": "/funchal/",
}
HEAD = ("<!-- QR-HEAD:START (generated by scripts/gen_qr.py) -->"
        '<script src="/qr.js"></script>'
        "<!-- QR-HEAD:END -->")

STUB = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex, follow">
<title>Levadinho</title>
<link rel="icon" href="/favicon.ico" sizes="any">
<script>
/* Levadinho QR code "{code}" (scripts/gen_qr.py): open {target} in the phone's language, marked as a scan. */
(function () {{
  var langs = ["pt", "fr", "de", "pl"], pick = "";
  var prefs = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || "en"];
  for (var i = 0; i < prefs.length; i++) {{
    var l = String(prefs[i]).slice(0, 2).toLowerCase();
    if (l === "en") break;
    if (langs.indexOf(l) >= 0) {{ pick = "/" + l; break; }}
  }}
  location.replace(pick + "{target}#qr={code}");
}})();
</script>
<style>body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:#FAFAF7;color:#16342A;padding:24px 16px;max-width:520px;margin:0 auto}}a{{color:#16342A;font-weight:700}}li{{margin:8px 0}}</style>
</head>
<body>
<p>Levadinho</p>
<ul>
{links}
</ul>
</body>
</html>
"""
LABEL = {"en": "English", "pt": "Português", "fr": "Français", "de": "Deutsch", "pl": "Polski"}


def write(path, data, mode="w"):
    old = open(path, "rb").read() if os.path.exists(path) else None
    new = data.encode("utf-8") if isinstance(data, str) else data
    if old != new:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, "wb").write(new)
        return True
    return False


def qr(url):
    q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_Q, border=4)
    q.add_data(url)
    q.make(fit=True)
    return q


def svg(q):
    import io
    buf = io.BytesIO()
    q.make_image(image_factory=SvgPathImage).save(buf)
    return buf.getvalue()


def png(q):
    import io
    from PIL import Image
    img = q.make_image(fill_color="#16342A", back_color="white").convert("RGB")
    img = img.resize((1200, 1200), Image.NEAREST)
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def add_head(path):
    s = open(path, encoding="utf-8").read()
    if "QR-HEAD:START" in s:
        new = re.sub(r"<!-- QR-HEAD:START.*?QR-HEAD:END -->", HEAD, s, count=1, flags=re.S)
    else:   # first thing after the CONFIG block, so it runs before any page script
        i = s.index("<title>")
        new = s[:i] + HEAD + "\n" + s[i:]
    return write(path, new)


def main():
    changed = []
    for code, target in CODES.items():
        assert re.fullmatch(r"[a-z0-9-]{1,30}", code), code
        url = f"{BASE}/q/{code}/"
        links = "\n".join(f'<li><a href="{PREFIX[l]}{target}#qr={code}">{LABEL[l]}</a></li>' for l in LANGS)
        out = os.path.join(ROOT, "q", code)
        if write(os.path.join(out, "index.html"), STUB.format(code=code, target=target, links=links)):
            changed.append(f"q/{code}/index.html")
        q = qr(url)
        if write(os.path.join(out, "qr.svg"), svg(q)):
            changed.append(f"q/{code}/qr.svg")
        if write(os.path.join(out, "qr.png"), png(q)):
            changed.append(f"q/{code}/qr.png")
        for l in LANGS:
            page = os.path.join(ROOT, PREFIX[l].lstrip("/"), target.strip("/"), "index.html")
            if not os.path.exists(page):
                sys.exit(f"FATAL: QR code {code}: target page {page} does not exist")
            if add_head(page):
                changed.append(os.path.relpath(page, ROOT))
        print(f"{code}: {url} -> {target}")
    print(f"{len(changed)} file(s) written" + (": " + ", ".join(changed) if changed else ""))


if __name__ == "__main__":
    main()
