#!/usr/bin/env python3
"""Write the "Ask Levadinho on WhatsApp" block into every page (all 5 languages).

Levadinho (the bot in bot/) only works on WhatsApp, so every page hands the visitor
over with:
  - a tap-to-open wa.me link (all screens), pre-filled with
        "Olá Levadinho! 👋 #web-<tag>"
    where the per-page tag tells the bot's analytics which page converted
    (bot/brain.py treats any `web-[a-z0-9-]{1,40}` tag as a source, not a guide route);
  - an inline SVG QR code of the same link, shown only on wider screens (a desktop
    visitor scans it with the phone that has WhatsApp). Generated here with the
    `qrcode` library, so the page needs no external file.

Two marker-delimited blocks, replaced in place on every run (idempotent):

  LEVADINHO-CTA-HEAD  before </head>   the block's CSS
  LEVADINHO-CTA       in the body      the block + a GoatCounter click event

A page with no LEVADINHO-CTA markers gets the block just before the first of: the
"Nearby trails" block, the "More guides" block, <footer>. To place it elsewhere, put
empty markers there by hand; later runs keep that spot.

Tags: same tag in every language (the bot detects the language itself). Trail pages use
their code (web-pr6, web-pr1-2, ...); guide pages have fixed short tags (TAGS below).
Not added to privacy/ or the trails/ redirect stubs. Fails loud on a page it can't tag.

    python scripts/gen_cta.py
"""

import pathlib
import re
import sys
import urllib.parse

import qrcode

ROOT = pathlib.Path(__file__).resolve().parent.parent
PHONE = "447405754593"          # Levadinho's WhatsApp number (+44 7405 754593)
GREETING = "Olá Levadinho! 👋 #{tag}"
LANG_DIRS = ("pt", "fr", "de", "pl")
SKIP_TOP = {"bot", "seo_research", ".claude", ".git", "https___madeira", "privacy", "trails", "img", "scripts", "node_modules"}

# Page (path inside its language folder) -> tag. Trail pages are tagged from their data-trail code.
TAGS = {
    "index.html": "web-home",
    "pr1/index.html": "web-pr1",
    "hiking-fees.html": "web-fees",
    "simplifica-from-abroad.html": "web-abroad",
    "getting-back.html": "web-back",
    "do-i-need-a-permit/index.html": "web-permit",
    "simplifica-booking/index.html": "web-booking",
    "pico-do-areeiro-weather/index.html": "web-weather",
    "pr1-sunrise-transport/index.html": "web-sunrise",
    "best-levada-walks/index.html": "web-best",
    "easy-levadas-no-vertigo/index.html": "web-easy",
    "levadas-with-tunnels/index.html": "web-tunnels",
}
WEB_TAG = re.compile(r"web-[a-z0-9-]{1,40}")   # must match bot/brain.py

TEXT = {
    "en": {"h": "Ask Levadinho on WhatsApp",
           "p": "Levadinho only works on WhatsApp — questions about trails, booking, getting back, in your language.",
           "btn": "Chat with Levadinho on WhatsApp", "cap": "Scan with your phone",
           "qr": "QR code that opens a WhatsApp chat with Levadinho"},
    "pt": {"h": "Pergunte ao Levadinho no WhatsApp",
           "p": "O Levadinho só funciona no WhatsApp — perguntas sobre percursos, reservas e como regressar, na sua língua.",
           "btn": "Falar com o Levadinho no WhatsApp", "cap": "Leia com o seu telemóvel",
           "qr": "Código QR que abre uma conversa com o Levadinho no WhatsApp"},
    "fr": {"h": "Demandez à Levadinho sur WhatsApp",
           "p": "Levadinho fonctionne uniquement sur WhatsApp — questions sur les sentiers, la réservation, le retour, dans votre langue.",
           "btn": "Discuter avec Levadinho sur WhatsApp", "cap": "Scannez avec votre téléphone",
           "qr": "QR code qui ouvre une conversation WhatsApp avec Levadinho"},
    "de": {"h": "Fragen Sie Levadinho auf WhatsApp",
           "p": "Levadinho gibt es nur auf WhatsApp — Fragen zu Wegen, Buchung und Rückweg, in Ihrer Sprache.",
           "btn": "Mit Levadinho auf WhatsApp chatten", "cap": "Mit dem Handy scannen",
           "qr": "QR-Code, der einen WhatsApp-Chat mit Levadinho öffnet"},
    "pl": {"h": "Zapytaj Levadinho na WhatsAppie",
           "p": "Levadinho działa tylko na WhatsAppie — pytania o szlaki, rezerwację i powrót, w twoim języku.",
           "btn": "Napisz do Levadinho na WhatsAppie", "cap": "Zeskanuj telefonem",
           "qr": "Kod QR otwierający czat z Levadinho na WhatsAppie"},
}

MARK = {k: ("<!-- {}:START (generated by scripts/gen_cta.py) -->".format(k), "<!-- {}:END -->".format(k))
        for k in ("LEVADINHO-CTA-HEAD", "LEVADINHO-CTA")}

CSS = """<style>
.lvd-cta{display:flex;gap:20px;align-items:center;justify-content:space-between;margin:26px 0 8px;padding:16px 18px 16px 20px;
  background:var(--card,#fff);border:1px solid var(--line,#E3E1D8);border-radius:12px;position:relative;overflow:hidden}
.lvd-cta::before{content:"";position:absolute;left:0;top:0;bottom:0;width:6px;
  background:linear-gradient(180deg,var(--way-yellow,#E8B71A) 0 50%,var(--way-red,#BE3A2B) 50% 100%)}
.lvd-cta h2{font-size:18px;margin:0 0 4px}
.lvd-cta p{margin:0 0 12px;color:var(--ink-soft,#4A5F56);font-size:14.5px}
.lvd-cta-btn{display:inline-block;background:var(--ink,#16342A);color:#fff !important;text-decoration:none;font-weight:700;
  font-size:15px;padding:10px 16px;border-radius:999px}
.lvd-cta-btn:hover{background:#0f261e}
.lvd-cta-qr{display:none;margin:0;text-align:center;flex:0 0 auto}
.lvd-cta-qr svg{display:block;width:124px;height:124px}
.lvd-cta-qr figcaption{font-size:12px;color:var(--ink-soft,#4A5F56);margin-top:4px}
@media (min-width:720px){.lvd-cta-qr{display:block}}
</style>"""


def page_lang_and_rel(path):
    rel = path.relative_to(ROOT).as_posix()
    first = rel.split("/")[0]
    if first in LANG_DIRS:
        return first, rel.split("/", 1)[1]
    return "en", rel


def tag_for(rel, html):
    if rel in TAGS:
        return TAGS[rel]
    m = re.search(r'id="statusCard"[^>]*data-trail="([^"]+)"', html)
    if m:
        return "web-" + m.group(1).lower().replace(".", "-")
    return None


def wa_url(tag):
    return "https://wa.me/{}?text={}".format(PHONE, urllib.parse.quote(GREETING.format(tag=tag), safe=""))


_QR = {}


def qr_svg(url, label):
    """A compact SVG: one <path> of horizontal runs of dark modules, with a 2-module quiet zone."""
    if url not in _QR:
        q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=2)
        q.add_data(url)
        q.make(fit=True)
        m = q.get_matrix()              # includes the border
        n = len(m)
        d = []
        for y, row in enumerate(m):
            x = 0
            while x < n:
                if row[x]:
                    x0 = x
                    while x < n and row[x]:
                        x += 1
                    d.append("M{} {}h{}v1h-{}z".format(x0, y, x - x0, x - x0))
                else:
                    x += 1
        _QR[url] = (n, "".join(d))
    n, d = _QR[url]
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {n} {n}" role="img" aria-label="{a}" shape-rendering="crispEdges">'
            '<rect width="{n}" height="{n}" fill="#fff"/><path fill="#16342A" d="{d}"/></svg>').format(n=n, a=label, d=d)


def block_html(lang, tag):
    T = TEXT[lang]
    url = wa_url(tag)
    href = url.replace("&", "&amp;")
    return (
        '<aside class="lvd-cta" aria-labelledby="lvd-cta-h">\n'
        '  <div>\n'
        '    <h2 id="lvd-cta-h">{h}</h2>\n'
        '    <p>{p}</p>\n'
        '    <a class="lvd-cta-btn" href="{href}" target="_blank" rel="noopener" data-tag="{tag}">{btn}</a>\n'
        '  </div>\n'
        '  <figure class="lvd-cta-qr">{svg}<figcaption>{cap}</figcaption></figure>\n'
        '</aside>\n'
        '<script>\n'
        '(function(){{var a=document.querySelector(".lvd-cta-btn");if(!a)return;\n'
        '  a.addEventListener("click",function(){{try{{var g=window.goatcounter;\n'
        '    if(g&&g.count)g.count({{path:"whatsapp-"+a.getAttribute("data-tag"),title:"Levadinho WhatsApp CTA",event:true}});}}catch(e){{}}}});}})();\n'
        '</script>'
    ).format(h=T["h"], p=T["p"], href=href, tag=tag, btn=T["btn"], svg=qr_svg(url, T["qr"]), cap=T["cap"])


def put(html, key, body, anchors, path):
    start, end = MARK[key]
    block = "{}\n{}\n{}".format(start, body, end)
    if start in html:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda _: block, html, count=1, flags=re.S)
    for a in anchors:
        i = html.find(a)
        if i >= 0:
            return html[:i] + block + "\n" + html[i:]
    sys.exit("FATAL: no anchor for {} in {}".format(key, path))


def pages():
    for p in sorted(ROOT.rglob("*.html")):
        parts = p.relative_to(ROOT).parts
        if parts[0] in SKIP_TOP or p.name.startswith("google"):
            continue
        if len(parts) > 1 and parts[0] in LANG_DIRS and parts[1] in ("trails", "privacy"):
            continue
        yield p


def main():
    n, tags = 0, {}
    for p in pages():
        lang, rel = page_lang_and_rel(p)
        html = p.read_text(encoding="utf-8")
        tag = tag_for(rel, html)
        if not tag or not WEB_TAG.fullmatch(tag):
            sys.exit("FATAL: no WhatsApp tag for {} -- add it to TAGS".format(p.relative_to(ROOT)))
        if tags.setdefault((lang, tag), rel) != rel:
            sys.exit("FATAL: tag {} used by both {} and {}".format(tag, tags[(lang, tag)], rel))
        html = put(html, "LEVADINHO-CTA-HEAD", CSS, ["<!-- SITE-NAV-HEAD:START", "</head>"], p)
        html = put(html, "LEVADINHO-CTA", block_html(lang, tag),
                   ["<!-- SITE-NAV-RELATED:START", "<!-- SITE-NAV-GUIDES:START", "<footer"], p)
        p.write_text(html, encoding="utf-8")
        n += 1
    print("WhatsApp CTA written to {} pages ({} tags)".format(n, len({t for _, t in tags})))


if __name__ == "__main__":
    main()
