#!/usr/bin/env python3
"""Write a static, crawlable list of every trail into the four dashboards.

Why this exists
---------------
The dashboard builds its trail cards client-side (`dashboard.js` sets
`#trailBoard.innerHTML`), so in the raw HTML that Googlebot reads first, the
hub linked to *nothing*. The whole site's static link graph was `/` <-> the
four `/trails/` pages -- and Search Console duly reported knowing 4 URLs out of
the 164 in the sitemap. The 36 spoke pages had no HTML path leading to them.

So: emit a real `<a href>` per trail inside `#trailBoard`, between marker
comments. Crawlers and no-JS visitors get a working index; `dashboard.js`
overwrites the whole container on load, so JS visitors never see it.

Re-runnable and idempotent -- run it again whenever `status.json` gains or
loses a trail:

    python scripts/gen_trail_index.py
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

START = "<!-- STATIC-TRAIL-INDEX:START (generated by scripts/gen_trail_index.py) -->"
END = "<!-- STATIC-TRAIL-INDEX:END -->"

# Heading above the static list, per language. Only ever seen by crawlers and
# no-JS visitors -- dashboard.js replaces the container on a successful load.
LANGS = {
    "": "All Madeira PR trails",
    "fr": "Tous les sentiers PR de Madère",
    "de": "Alle PR-Wanderwege Madeiras",
    "pl": "Wszystkie szlaki PR na Maderze",
}


def localise(page: str, lang: str) -> str:
    """Map an English spoke path onto its `fr/`, `de/` or `pl/` twin."""
    if not lang:
        return page
    return "/{}/".format(lang) if page == "/" else "/{}{}".format(lang, page)


def block(trails: list, lang: str) -> str:
    items = "\n".join(
        '      <li><a href="{}">{} — {}</a></li>'.format(
            localise(t["page"], lang), t["code"], t["name"]
        )
        for t in trails
    )
    return (
        "{start}\n"
        '    <nav class="tindex" aria-label="{heading}">\n'
        "      <h2>{heading}</h2>\n"
        "      <ul>\n{items}\n      </ul>\n"
        "    </nav>\n"
        "    {end}"
    ).format(start=START, end=END, heading=LANGS[lang], items=items)


def main() -> None:
    trails = json.loads((ROOT / "status.json").read_text())["trails"]
    missing = [t["code"] for t in trails if not t.get("page")]
    if missing:
        sys.exit("FATAL: trails with no page, cannot link them: {}".format(missing))

    for lang in LANGS:
        path = ROOT / lang / "trails" / "index.html" if lang else ROOT / "trails" / "index.html"
        html = path.read_text()
        new = block(trails, lang)

        if START in html:
            html = re.sub(
                re.escape(START) + r".*?" + re.escape(END), new, html, flags=re.S
            )
        else:
            # First run: append the block inside the existing #trailBoard, after
            # the "Loading trails…" placeholder, leaving that placeholder alone.
            m = re.search(r'(<div id="trailBoard">)(.*?)(</div>)', html, flags=re.S)
            if not m:
                sys.exit("FATAL: #trailBoard container not found in {}".format(path))
            html = (
                html[: m.end(2)] + "\n    " + new + "\n  " + html[m.start(3):]
            )

        path.write_text(html)
        print("{}: {} trail links".format(path.relative_to(ROOT), len(trails)))


if __name__ == "__main__":
    main()
