#!/usr/bin/env python3
"""Inject the site-wide navigation into every page: a top nav bar, breadcrumbs
(visible + BreadcrumbList JSON-LD) and a "Nearby trails" block on each trail.

Why this exists
---------------
A Screaming Frog crawl (2026-09-28) showed the static link graph was too thin:
the fees and booking-from-abroad pages were reachable only from each other (8
orphans), most spokes had just 5 inbound links (4 language switchers + the
board), and trail pages had no route to their neighbours. This script gives
every page the same crawlable links, all as plain `<a href>` in the raw HTML.

Four marker-delimited blocks, replaced in place on every run (idempotent):

  SITE-NAV-HEAD     before </head>   CSS + BreadcrumbList JSON-LD
  SITE-NAV          in <header>      nav bar + breadcrumb trail
  SITE-NAV-RELATED  before <footer>  4 nearest trails (trail pages only)

"Nearby" is real distance between trailheads, from the coordinates embedded in
the Visit Madeira hiking index (the same source `update_status.py` parses).
Fails loud if that index can't be read.

Re-run after `gen_spokes.py` (which calls this itself) or whenever a trail or
page is added:

    python scripts/gen_site_nav.py
"""

import json
import math
import pathlib
import re
import sys

import requests

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The Visit Madeira hiking index and its row pattern (same source as
# update_status.py; kept local so this script doesn't depend on that module's
# internal names). Rows: ["PR X - Name", lat, lon, n, "img", "url", "", bool, {"label":"..."}]
TRAILS_INDEX = "https://visitmadeira.com/en/what-to-do/nature-seekers/activities/hiking/"
TRAIL_RE = re.compile(
    r'\["(PR[^"]+?)",(-?\d+\.\d+),(-?\d+\.\d+),\d+,"[^"]*","[^"]*","[^"]*",'
    r'(?:true|false),\{"label":"([^"]+)"'
)
UA = {"User-Agent": "Mozilla/5.0 (compatible; LevadinhoStatusBot/5.0; +https://levadinho-madeira.com)"}

BASE = "https://levadinho-madeira.com"
LANGS = ("en", "pt", "fr", "de", "pl")
PREFIX = {"en": "", "pt": "/pt", "fr": "/fr", "de": "/de", "pl": "/pl"}
N_RELATED = 4

MARK = {
    k: ("<!-- {}:START (generated by scripts/gen_site_nav.py) -->".format(k),
        "<!-- {}:END -->".format(k))
    for k in ("SITE-NAV-HEAD", "SITE-NAV", "SITE-NAV-RELATED")
}

# Nav bar entries: key -> (path within the language folder, label per language)
NAV = [
    ("trails", "/", {"en": "All trails", "pt": "Todos os percursos", "fr": "Tous les sentiers", "de": "Alle Wanderwege", "pl": "Wszystkie szlaki"}),
    ("pr1", "/pr1/", {"en": "PR1 today", "pt": "PR1 hoje", "fr": "PR1 aujourd'hui", "de": "PR1 heute", "pl": "PR1 dziś"}),
    ("fees", "/hiking-fees.html", {"en": "Fees 2026", "pt": "Taxas 2026", "fr": "Tarifs 2026", "de": "Gebühren 2026", "pl": "Opłaty 2026"}),
    ("booking", "/simplifica-from-abroad.html", {"en": "Booking from abroad", "pt": "Reservar do estrangeiro", "fr": "Réserver depuis l'étranger",
                                                 "de": "Buchen aus dem Ausland", "pl": "Rezerwacja z zagranicy"}),
    ("back", "/getting-back.html", {"en": "Getting back from PR1", "pt": "Regressar do PR1", "fr": "Retour du PR1",
                                    "de": "Rückweg vom PR1", "pl": "Powrót z PR1"}),
]
NAV_ARIA = {"en": "Site", "pt": "Site", "fr": "Site", "de": "Website", "pl": "Serwis"}
CRUMB_ARIA = {"en": "Breadcrumb", "pt": "Navegação estrutural", "fr": "Fil d'Ariane", "de": "Brotkrümelnavigation", "pl": "Ścieżka nawigacji"}
HOME = {"en": "Home", "pt": "Início", "fr": "Accueil", "de": "Startseite", "pl": "Strona główna"}
NEARBY = {"en": "Nearby trails", "pt": "Percursos próximos", "fr": "Sentiers à proximité", "de": "Wanderwege in der Nähe", "pl": "Szlaki w pobliżu"}
NEARBY_SUB = {"en": "Closest trailheads — each has its own live status.",
              "pt": "Os pontos de partida mais próximos — cada um com o seu estado em direto.",
              "fr": "Les départs les plus proches — chacun avec son état en direct.",
              "de": "Die nächstgelegenen Startpunkte — jeweils mit eigenem Live-Status.",
              "pl": "Najbliższe punkty startowe — każdy z własnym stanem na żywo."}
KM = {"en": "{} km away", "pt": "a {} km", "fr": "à {} km", "de": "{} km entfernt", "pl": "{} km stąd"}
SAME = {"en": "Same trailhead", "pt": "Mesmo ponto de partida", "fr": "Même point de départ", "de": "Gleicher Startpunkt", "pl": "Ten sam punkt startowy"}


def dist_label(lang, d):
    if d < 0.5:
        return SAME[lang]
    n = str(round(d, 1) if d < 10 else round(d))
    return KM[lang].format(n if lang == "en" else n.replace(".", ","))

CSS = """<style>
.sitenav{display:flex;flex-wrap:wrap;gap:4px 16px;margin:10px 0 8px;font-size:13.5px}
.sitenav a{color:var(--ink);font-weight:650;text-decoration:none;border-bottom:2px solid transparent;padding-bottom:1px}
.sitenav a:hover{border-bottom-color:var(--line,#E3E1D8)}
.sitenav a[aria-current="page"]{border-bottom-color:var(--way-yellow,#E8B71A)}
.crumbs ol{list-style:none;padding:0;margin:0 0 4px;display:flex;flex-wrap:wrap}
.crumbs li{margin:0;font-size:12.5px;color:var(--ink-soft)}
.crumbs li+li::before{content:"\\203A";margin:0 7px;color:var(--ink-soft)}
.crumbs a{color:var(--ink-soft)}
.related ul{list-style:none;padding:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
@media (max-width:480px){.related ul{grid-template-columns:1fr}}
.related li{margin:0}
.related a{display:block;height:100%;background:var(--card,#fff);border:1px solid var(--line,#E3E1D8);border-radius:10px;
  padding:10px 12px;text-decoration:none;color:var(--ink);font-weight:700;font-size:14.5px;line-height:1.3}
.related a:hover{border-color:var(--ink-soft)}
.related a span{display:block;margin-top:3px;font-weight:400;font-size:12.5px;color:var(--ink-soft)}
.related p{color:var(--ink-soft);font-size:14px}
a.tname{color:inherit;text-decoration:none}
a.tname:hover{text-decoration:underline}
</style>"""


def trail_coords():
    """code -> (lat, lon) of each trailhead, from the Visit Madeira index."""
    r = requests.get(TRAILS_INDEX, headers=UA, timeout=30)
    r.raise_for_status()
    out = {}
    for m in TRAIL_RE.finditer(r.text):
        try:
            raw = json.loads('"' + m.group(1) + '"')
        except Exception:
            raw = m.group(1)
        code = (raw.split(" - ", 1)[0] if " - " in raw else raw).replace(" ", "")
        out.setdefault(code, (float(m.group(2)), float(m.group(3))))
    return out


def km(a, b):
    """Great-circle distance in km."""
    la1, lo1, la2, lo2 = map(math.radians, (*a, *b))
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 2 * 6371 * math.asin(math.sqrt(h))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def href(lang, path):
    """Root-relative URL of `path` (an English path) in `lang`'s folder."""
    return PREFIX[lang] + path


def file_for(lang, path):
    rel = path.lstrip("/")
    rel = rel + "index.html" if rel.endswith("/") or rel == "" else rel
    return ROOT / PREFIX[lang].lstrip("/") / rel if PREFIX[lang] else ROOT / rel


def replace_block(html, key, body, anchor_re, where, path):
    """Put `body` between `key`'s markers: in place if present, otherwise
    before/after the first match of `anchor_re`."""
    start, end = MARK[key]
    block = "{}\n{}\n{}".format(start, body, end)
    if start in html:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda _: block, html, count=1, flags=re.S)
    m = re.search(anchor_re, html, flags=re.S)
    if not m:
        sys.exit("FATAL: anchor {!r} for {} not found in {}".format(anchor_re, key, path))
    i = m.start() if where == "before" else m.end()
    return html[:i] + block + "\n" + html[i:]


def nav_html(lang, current, crumbs):
    items = "\n".join(
        '    <a href="{}"{}>{}</a>'.format(href(lang, p), ' aria-current="page"' if k == current else "", esc(lbl[lang]))
        for k, p, lbl in NAV
    )
    out = '  <nav class="sitenav" aria-label="{}">\n{}\n  </nav>'.format(NAV_ARIA[lang], items)
    if crumbs:
        lis = []
        for i, (name, url) in enumerate(crumbs):
            if i == len(crumbs) - 1:
                lis.append('      <li aria-current="page">{}</li>'.format(esc(name)))
            else:
                lis.append('      <li><a href="{}">{}</a></li>'.format(url, esc(name)))
        out += '\n  <nav class="crumbs" aria-label="{}">\n    <ol>\n{}\n    </ol>\n  </nav>'.format(
            CRUMB_ARIA[lang], "\n".join(lis))
    return out


def head_html(crumbs):
    if not crumbs:
        return CSS
    ld = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": BASE + url}
            for i, (name, url) in enumerate(crumbs)
        ],
    }
    return CSS + '\n<script type="application/ld+json">\n{}\n</script>'.format(
        json.dumps(ld, ensure_ascii=False, indent=2))


def related_html(lang, near):
    items = "\n".join(
        '    <li><a href="{}">{} {}<span>{}</span></a></li>'.format(
            href(lang, t["page"]), esc(t["code"]), esc(t["name"]), dist_label(lang, d))
        for t, d in near
    )
    return ('<section class="related" id="nearby">\n  <h2>{}</h2>\n  <p>{}</p>\n  <ul>\n{}\n  </ul>\n</section>'
            .format(NEARBY[lang], NEARBY_SUB[lang], items))


SKIPPED = []


def process(path, lang, current, crumbs, near=None, header_anchor=r'<nav class="langs"[^>]*>.*?</nav>\n'):
    if not path.exists():
        # A language's page may not exist yet (pt/ is being rolled out page by
        # page) -- skip it and say so; re-run once the file is there.
        SKIPPED.append(str(path.relative_to(ROOT)))
        return False
    html = path.read_text(encoding="utf-8")
    html = replace_block(html, "SITE-NAV-HEAD", head_html(crumbs), r"</head>", "before", path)
    html = replace_block(html, "SITE-NAV", nav_html(lang, current, crumbs), header_anchor, "after", path)
    if near:
        html = replace_block(html, "SITE-NAV-RELATED", related_html(lang, near), r"<footer", "before", path)
    path.write_text(html, encoding="utf-8")
    return True


def main():
    trails = json.loads((ROOT / "status.json").read_text())["trails"]
    coords = trail_coords()
    missing = [t["code"] for t in trails if t["code"] not in coords or not t.get("page")]
    if missing:
        sys.exit("FATAL: no coordinates or page for {}".format(missing))

    def nearest(t):
        others = [(o, km(coords[t["code"]], coords[o["code"]])) for o in trails if o["page"] != t["page"]]
        return sorted(others, key=lambda x: x[1])[:N_RELATED]

    n = 0
    for lang in LANGS:
        home = (HOME[lang], href(lang, "/"))   # the homepage is the trails board
        for t in trails:
            name = "{} {}".format(t["code"], t["name"])
            n += process(file_for(lang, t["page"]), lang, "pr1" if t["page"] == "/pr1/" else None,
                         [home, (name, href(lang, t["page"]))], nearest(t))
        n += process(file_for(lang, "/"), lang, "trails", None)
        for key, p, lbl in NAV[2:]:
            n += process(file_for(lang, p), lang, key, [home, (lbl[lang], href(lang, p))])
    # English-only privacy page: nav bar only, no language switcher to anchor on.
    process(ROOT / "privacy" / "index.html", "en", None, None, header_anchor=r"<header>\n")
    print("site nav written to {} pages (+ privacy)".format(n))
    if SKIPPED:
        print("skipped {} missing page(s) -- re-run once they exist: {}".format(len(SKIPPED), ", ".join(SKIPPED)))


if __name__ == "__main__":
    main()
